### ISSUE TITLE
flip_filters = True / False

### ISSUE THREAD

**Issue by htzheng** [Ignotus/theano-flownet#2]
When training the theano-flownet, I observed that using the original code causes exploding gradients. However, after setting _flip_filters_ option in leaky_deconv() and upsample() layer to _False_, the Theano training works.

So I just wonder is the _flip_filters=true_ necessary for leaky_deconv() and upsample() ? Is this option for importing Caffe weights?

Thank you

**Comment by Ignotus** [comment]
Hi,

I am not sure about that, if you do with flip_filters=False a network will produce quite poor results on optical flow.
